AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.testehan::SpringBoot3AwsLambda

Globals:
  Function:
    Runtime: java17
    MemorySize: 2048
    Timeout: 29

Resources:
  BlogPostsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  SpringBoot3AwsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.testehan.StreamLambdaHandler::handleRequest
      CodeUri: target/SpringBoot3AwsLambda-1.0-SNAPSHOT-lambda-package.zip
      AutoPublishAlias: live
      SnapStart:
          ApplyOn: PublishedVersions
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBoot3AwsLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringBoot3AwsLambdaApi
